#!/bin/sh
# Persist OS Claude Code UserPromptSubmit hook.
# Generated by `persist init`. Looks up context cards for the submitted prompt and injects
# pointers (never whole files) into the prompt. Read-only: the prompt text stays in this
# process and is never written to disk or logged.
# Wired in .claude/settings.json; that file decides the timeout.
input=$(cat)
if command -v persist >/dev/null 2>&1; then
  printf '%s' "$input" | persist context --hook claude
elif [ -x node_modules/.bin/persist ]; then
  printf '%s' "$input" | node_modules/.bin/persist context --hook claude
fi
exit 0
