#!/bin/sh
# Persist OS Claude Code SessionStart hook.
# Generated by `persist init`. Injects a repository-memory map into every Claude Code session so a
# fresh agent reliably loads durable memory. Wired in .claude/settings.json. Read-only.

adrs=$(ls docs/adrs/ADR-*.md 2>/dev/null | sed 's|.*/||;s|\.md$||' | tr '\n' ' ')
modules=$(ls -d docs/30-modules/*/ 2>/dev/null | sed 's|docs/30-modules/||;s|/$||' | tr '\n' ' ')

# Fence index: one flattened line of "## <path>" / "Why: <reason>" lines from FENCES.md.
# A missing file means no fence crossed yet (FENCES.md is never required), and an empty index
# injects nothing — silence is the correct signal in both cases.
base="Persist OS repository memory is the source of truth over chat history. Before non-trivial work, read AGENTS.md and the docs it routes to; repository rules override model preference. Accepted ADRs (docs/adrs/): ${adrs:-none yet}. Modules (docs/30-modules/): ${modules:-none yet}. Use the Persist OS CLI commands listed in AGENTS.md (persist feature/adr/module create, persist adr accept and supersede, persist doctor) yourself; do not web-search them. Run 'persist doctor' before claiming work complete."
context="$base"
full=$(grep -e '^## ' -e '^Why: ' docs/60-engineering/FENCES.md 2>/dev/null | tr '\n' ' ' | sed 's/\\/\\\\/g; s/"/\\"/g')
if [ -n "$full" ]; then
  label=" Chesterton fence index (recorded rationale; full history in docs/60-engineering/FENCES.md): "
  loaded=$(cat CLAUDE.md AGENTS.md .cursor/rules/persist-memory.mdc 2>/dev/null | wc -c | tr -d ' ')
  room=$((24576 - loaded - $(printf '%s' "$base" | wc -c | tr -d ' ') - $(printf '%s' "$label" | wc -c | tr -d ' ')))
  marker="... (fence index truncated to the context budget; read docs/60-engineering/FENCES.md)"
  m=$(printf '%s' "$marker" | wc -c | tr -d ' ')
  if [ "$room" -le 0 ]; then
    fences="$marker"
  elif [ "$(printf '%s' "$full" | wc -c | tr -d ' ')" -le "$room" ]; then
    fences="$full"
  else
    keep=$((room - m))
    if [ "$keep" -lt 0 ]; then
      keep=0
    fi
    fences="$(printf '%s' "$full" | head -c "$keep" | sed 's/\\*$//')$marker"
  fi
  context="$base$label$fences"
fi

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$context"
