#!/bin/sh
# Persist OS Claude Code SessionStart hook.
# Generated by `persist init`. Injects a repository-memory map into every Claude Code session so a
# fresh agent reliably loads durable memory. Wired in .claude/settings.json. Read-only.

# Memory locations come from .persist/config.json, so a relocated docs folder keeps loading
# without regenerating this file. A missing config or key falls back to the default layout.
config_dir() {
  value=$(sed -n 's/.*"'"$1"'": *"\([^"]*\)".*/\1/p' .persist/config.json 2>/dev/null | head -n 1)
  # A backslash can only come from a JSON-escaped quote, which a path read this way cannot
  # represent; fall back rather than inject it into the JSON below.
  case "$value" in *\\*) value="" ;; esac
  printf '%s' "${value:-$2}"
}
docs_dir=$(config_dir docsDir docs)
adr_dir=$(config_dir adrDir docs/adrs)
modules_dir=$(config_dir modulesDir docs/30-modules)
fences_file="$docs_dir/60-engineering/FENCES.md"

# ADR standing in a single awk pass over the ADR files: each file's whole ## Status
# section (every line up to the next ## heading, case-insensitive, CR stripped)
# decides its list, matching adrStandingOf — the section holds accepted as a word with
# no superseded-by prints A:<name>, holding proposed prints P:<name>, anything else
# prints nothing. Drafts under proposed/ count as proposed by location, the way doctor
# reads them.
adr_classes=$(ls "$adr_dir"/ADR-*.md 2>/dev/null | awk '
  {
    file = $0
    section = ""
    in_status = 0
    while ((getline line < file) > 0) {
      stripped = line
      sub("\r$", "", stripped)
      t = stripped
      sub(/^[[:blank:]]+/, "", t)
      sub(/[[:blank:]]+$/, "", t)
      if (in_status) {
        if (stripped ~ /^##[[:space:]]/) {
          in_status = 0
        } else {
          section = (section == "" ? t : section "\n" t)
        }
      } else if (tolower(t) == "## status") {
        in_status = 1
      }
    }
    close(file)
    name = file
    sub(/.*\//, "", name)
    sub(/\.md$/, "", name)
    s = tolower(section)
    negated = (s ~ /(^|[^[:alnum:]_])(not[[:space:]][[:space:]]*(yet[[:space:]][[:space:]]*)?accepted|never[[:space:]][[:space:]]*accepted|unaccepted)([^[:alnum:]_]|$)/)
    if (s ~ /(^|[^[:alnum:]_])accepted([^[:alnum:]_]|$)/ && !negated && s !~ /superseded[[:space:]][[:space:]]*by/) {
      printf "A:%s\n", name
    } else if (s ~ /proposed/) {
      printf "P:%s\n", name
    }
  }')
adrs=$(printf '%s\n' "$adr_classes" | sed -n 's/^A://p' | tr '\n' ' ' | sed 's/\\/\\\\/g; s/"/\\"/g')
proposed=$(printf '%s\n' "$adr_classes" | sed -n 's/^P://p' | tr '\n' ' ')
proposed_drafts=$(ls "$adr_dir"/proposed/ADR-PROPOSED-*.md 2>/dev/null | sed 's|.*/||;s|\.md$||' | tr '\n' ' ')
proposed="$proposed$proposed_drafts"
proposed=$(printf '%s' "$proposed" | sed 's/\\/\\\\/g; s/"/\\"/g')
# The Proposed list rides the base context right after the Accepted list, only when
# non-empty — so it counts toward the same always-loaded budget through the base bytes.
proposed_adrs=""
if [ -n "$proposed" ]; then
  proposed_adrs=" Proposed ADRs, pending review, not binding: $proposed."
fi
modules=$(ls -d "$modules_dir"/*/ 2>/dev/null | sed 's|/$||;s|.*/||' | tr '\n' ' ')

# Fence index: one flattened line of "## <path>" / "Why: <reason>" lines from FENCES.md.
# Only entries with a Why: line are listed: a No constraint: entry answers nothing an agent
# needs before editing, so its heading stays out. With no such entries the awk prints exactly
# what the old grep printed, byte for byte. A missing file means no fence crossed yet
# (FENCES.md is never required), and an empty index injects nothing — silence is the correct
# signal in both cases.
base="Persist OS repository memory is the source of truth over chat history. Before non-trivial work, read AGENTS.md and the docs it routes to; repository rules override model preference. Accepted ADRs (${adr_dir}/): ${adrs:-none yet}.${proposed_adrs} Modules (${modules_dir}/): ${modules:-none yet}. Use the Persist OS CLI commands listed in AGENTS.md (persist feature/adr/module create, persist adr accept and supersede, persist doctor) yourself, as 'npx persist-os <command>' if persist is not installed; do not web-search them. Before calling work done, check the diff against every accepted ADR governing the files you changed (read its Decision, not just its title); work is done when 'persist doctor' reports no errors, the tests pass, and every warning is fixed or listed under Needs your review with what the human has to decide ('PASSED' is the goal). When you finish work in an area, create or update its context card — above all the Answers list, with the task you were just given phrased the way it was asked."
context="$base"
full=$(awk '/^## /{h=$0; next} /^Why: /{if (h != "") print h; print; h=""; next} /^No constraint:/{h=""; next}' "$fences_file" 2>/dev/null | tr '\n' ' ' | sed 's/\\/\\\\/g; s/"/\\"/g')
lessons_file="$docs_dir/60-engineering/LESSONS.md"
always=$(tr -d '\r' < "$lessons_file" 2>/dev/null | awk 'BEGIN{w=0} /^##[ \t]/{w=(tolower($0) ~ /^##[ \t]+always[ \t]*$/);next} w{print}' | sed -e 's/<!--.*-->//g' -e 's/^[[:space:]]*[-*][[:space:]]*//' -e 's/^[[:space:]]*//' | tr '\n\t' '  ' | sed -e 's/  */ /g' -e 's/^ //' -e 's/ $//' -e 's/\\/\\\\/g' -e 's/"/\\"/g')
if [ -n "$always" ]; then
  always="$always "
fi
if [ -n "$full" ]; then
  label=" Chesterton fence index (recorded rationale; full history in ${fences_file}): "
  loaded=$(cat CLAUDE.md AGENTS.md .cursor/rules/persist-memory.mdc 2>/dev/null | wc -c | tr -d ' ')
  alen=0
  abytes=0
  if [ -n "$always" ]; then
    alen=$(printf '%s' " Always lessons: " | wc -c | tr -d ' ')
    abytes=$(printf '%s' "$always" | wc -c | tr -d ' ')
  fi
  room=$((24576 - loaded - $(printf '%s' "$base" | wc -c | tr -d ' ') - $(printf '%s' "$label" | wc -c | tr -d ' ') - $alen - $abytes))
  marker="... (fence index truncated to the context budget; read ${fences_file})"
  m=$(printf '%s' "$marker" | wc -c | tr -d ' ')
  if [ "$room" -le 0 ]; then
    fences="$marker"
  elif [ "$(printf '%s' "$full" | wc -c | tr -d ' ')" -le "$room" ]; then
    fences="$full"
  else
    keep=$((room - m))
    if [ "$keep" -lt 0 ]; then
      keep=0
    fi
    fences="$(printf '%s' "$full" | head -c "$keep" | sed 's/\\*$//')$marker"
  fi
  context="$base$label$fences"
fi
if [ -n "$always" ]; then
  alabel=" Always lessons: "
  amarker="... (always lessons truncated to the context budget; read ${lessons_file})"
  aloaded=$(cat CLAUDE.md AGENTS.md .cursor/rules/persist-memory.mdc 2>/dev/null | wc -c | tr -d ' ')
  aused=$(printf '%s' "$context" | wc -c | tr -d ' ')
  aroom=$((24576 - aloaded - aused - $(printf '%s' "$alabel" | wc -c | tr -d ' ')))
  am=$(printf '%s' "$amarker" | wc -c | tr -d ' ')
  if [ "$aroom" -le 0 ]; then
    lessons="$amarker"
  elif [ "$(printf '%s' "$always" | wc -c | tr -d ' ')" -le "$aroom" ]; then
    lessons="$always"
  else
    akeep=$((aroom - am))
    if [ "$akeep" -lt 0 ]; then
      akeep=0
    fi
    lessons="$(printf '%s' "$always" | head -c "$akeep" | sed 's/\\*$//')$amarker"
  fi
  context="$context$alabel$lessons"
fi

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$context"
