#!/bin/sh
# Persist OS Claude Code SessionStart hook.
# Generated by `persist init`. Injects a repository-memory map into every Claude Code session so a
# fresh agent reliably loads durable memory. Wired in .claude/settings.json. Read-only.

# Memory locations come from .persist/config.json, so a relocated docs folder keeps loading
# without regenerating this file. A missing config or key falls back to the default layout.
config_dir() {
  value=$(sed -n 's/.*"'"$1"'": *"\([^"]*\)".*/\1/p' .persist/config.json 2>/dev/null | head -n 1)
  # A backslash can only come from a JSON-escaped quote, which a path read this way cannot
  # represent; fall back rather than inject it into the JSON below.
  case "$value" in *\\*) value="" ;; esac
  printf '%s' "${value:-$2}"
}
docs_dir=$(config_dir docsDir docs)
adr_dir=$(config_dir adrDir docs/adrs)
modules_dir=$(config_dir modulesDir docs/30-modules)
fences_file="$docs_dir/60-engineering/FENCES.md"

adrs=$(ls "$adr_dir"/ADR-*.md 2>/dev/null | sed 's|.*/||;s|\.md$||' | tr '\n' ' ')
modules=$(ls -d "$modules_dir"/*/ 2>/dev/null | sed 's|/$||;s|.*/||' | tr '\n' ' ')

# Fence index: one flattened line of "## <path>" / "Why: <reason>" lines from FENCES.md.
# A missing file means no fence crossed yet (FENCES.md is never required), and an empty index
# injects nothing — silence is the correct signal in both cases.
base="Persist OS repository memory is the source of truth over chat history. Before non-trivial work, read AGENTS.md and the docs it routes to; repository rules override model preference. Accepted ADRs (${adr_dir}/): ${adrs:-none yet}. Modules (${modules_dir}/): ${modules:-none yet}. Use the Persist OS CLI commands listed in AGENTS.md (persist feature/adr/module create, persist adr accept and supersede, persist doctor) yourself, as 'npx persist-os <command>' if persist is not installed; do not web-search them. Work is done only when 'persist doctor' reports PASSED."
context="$base"
full=$(grep -e '^## ' -e '^Why: ' "$fences_file" 2>/dev/null | tr '\n' ' ' | sed 's/\\/\\\\/g; s/"/\\"/g')
if [ -n "$full" ]; then
  label=" Chesterton fence index (recorded rationale; full history in ${fences_file}): "
  loaded=$(cat CLAUDE.md AGENTS.md .cursor/rules/persist-memory.mdc 2>/dev/null | wc -c | tr -d ' ')
  room=$((24576 - loaded - $(printf '%s' "$base" | wc -c | tr -d ' ') - $(printf '%s' "$label" | wc -c | tr -d ' ')))
  marker="... (fence index truncated to the context budget; read ${fences_file})"
  m=$(printf '%s' "$marker" | wc -c | tr -d ' ')
  if [ "$room" -le 0 ]; then
    fences="$marker"
  elif [ "$(printf '%s' "$full" | wc -c | tr -d ' ')" -le "$room" ]; then
    fences="$full"
  else
    keep=$((room - m))
    if [ "$keep" -lt 0 ]; then
      keep=0
    fi
    fences="$(printf '%s' "$full" | head -c "$keep" | sed 's/\\*$//')$marker"
  fi
  context="$base$label$fences"
fi

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$context"
