export type SkillScript = {
  /** Repo-relative path inside the skill directory, e.g. `scripts/scan-secrets.sh`. */
  path: string;
  content: string;
  executable: boolean;
};

export type SkillDefinition = {
  name: string;
  title: string;
  /** WHAT the skill does and WHEN it activates. The router: read before the body loads. */
  description: string;
  /** One sentence: the single job this skill performs. */
  goal: string;
  /** Only inputs that are not obvious. Omitted when everything the skill needs is obvious. */
  inputs?: string[];
  /** 5–10 numbered steps. */
  workflow: string[];
  /** If X → do Y. Omitted when the workflow has no branches worth naming. */
  decisions?: string[];
  /** How the agent knows it is done. */
  verification: string[];
  /** One-hop links (`For X → docs/...`) followed only when the workflow reaches them. */
  resources: string[];
  /** What the skill hands back. */
  output: string[];
  /** Optional executable companions. A skill must work with these deleted. */
  scripts?: SkillScript[];
};

const SECRET_SCAN_SCRIPT = `#!/bin/sh
# scan-secrets.sh — read-only scan of a diff for candidate secrets.
#
# Usage: scan-secrets.sh [--staged | --file PATH]
#
# Reads the staged diff by default, or a unified diff file with --file PATH.
# Prints matching lines and exits 1 when candidates are found; exits 0 when
# clean. Reads only: it runs git and grep, writes nothing, and opens no
# connections.
set -eu

MODE="staged"
TARGET=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --staged)
      MODE="staged"
      ;;
    --file)
      MODE="file"
      TARGET="\${2:?missing path after --file PATH}"
      ;;
    *)
      printf 'usage: scan-secrets.sh [--staged | --file PATH]\\n'
      exit 2
      ;;
  esac
  shift
done

PATTERN='BEGIN [A-Z ]*PRIVATE KEY|AKIA[0-9A-Z]{16}|xox[bpas]-[0-9A-Za-z-][0-9A-Za-z-]*|ghp_[0-9A-Za-z]{36}|password[[:space:]]*[:=][[:space:]]*["'\\'']'

if [ "$MODE" = "file" ]; then
  MATCHES="$(grep -nEi -e "$PATTERN" -- "$TARGET" || true)"
else
  MATCHES="$(git diff --cached | grep -nEi -e "$PATTERN" || true)"
fi

if [ -z "$MATCHES" ]; then
  printf 'scan-secrets: no candidate secrets found.\\n'
  exit 0
fi

printf 'scan-secrets: candidate secrets found:\\n'
printf '%s\\n' "$MATCHES"
exit 1
`;

/**
 * The shared Stop and ask list, defined once in AGENTS.md. Skills that can make
 * or approve a change link to it from their last workflow step and Resources
 * rather than copying it, so the triggers stay identical everywhere.
 */
const STOP_AND_ASK_STEP =
  "Apply the shared Stop and ask list before continuing past any trigger (see AGENTS.md); when working unattended, follow its Working unattended section instead of waiting.";

const STOP_AND_ASK_RESOURCE = "For the shared Stop and ask list → AGENTS.md";

/**
 * Built-in catalog of Persist OS workflow skills (ADR-0008, ADR-0016).
 *
 * Twelve skills against the progressive-disclosure shape: no `Required Reading`,
 * resources as one-hop links, earned sections, and explicit verification and
 * output. Descriptions carry WHAT and WHEN with trigger language plus a Skip for
 * clause naming the neighbours, so agents invoke them at the right moment and
 * routing never overlaps. (`capture-mcp-context` is generated by
 * `persist mcp add`, not shipped in this catalog.)
 */
export const SKILL_CATALOG: SkillDefinition[] = [
  {
    name: "implement-task",
    title: "Implement Task",
    description:
      "Make a code change with the five-step loop: start from the pointers and governing decisions, keep it small, add focused checks, and update the area card. Use when implementing any code change inside decided ground. Skip for feature planning, ADR writing, drift reviews, security reviews, and module docs.",
    goal: "Land the smallest safe change for the task, with proof it holds.",
    workflow: [
      'Start from the pointers: run `persist context "<task>"` (or the Start here block) and open those files plus what the task needs; do not survey the repository.',
      "The Always lessons load every session; the lessons for your area arrive with the pointers. If they don't cover what you're doing, open the section of `LESSONS.md` that does (the pointers list them).",
      "Read the Decision section of each governing ADR (`persist doctor` names them); every accepted ADR still binds, and when a card disagrees with an ADR, the ADR wins.",
      "Make the smallest safe change that satisfies the task; match ceremony to scope and write no planning docs for a fix inside decided ground.",
      "Add focused tests for the behavior touched (the write-tests skill holds the procedure).",
      "Before calling it done, check each changed line against every governing decision, then run the tests and doctor; add the task to the area card's Answers list, phrased as asked.",
      "When something breaks non-obviously, add a one-line lesson. Put it under the area it belongs to (create the area with an Applies To list if none fits). Put it under Always only if every task in this repository needs it. When a regression test or a CONVENTIONS rule now enforces a lesson, move it there or delete it, and name the test or rule in the commit. Delete a lesson that describes a temporary state once that state is fixed.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If the task conflicts with an accepted ADR or engineering standards → stop and ask a human.",
      "If the change needs a new dependency, service, or data store no ADR covers → stop and ask; record it with `persist adr create`.",
      "If the request grows into a new feature, module, or data model → stop and plan it with the plan-feature skill instead.",
    ],
    verification: [
      "Every changed line follows each governing decision, or the conflict was resolved with a human.",
      "Focused tests cover the behavior touched and pass, with the test and doctor runs as evidence.",
      "The area card's Answers list holds the finished task phrased as asked.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For accepted decisions and the paths each one governs (its Applies To section) → docs/adrs/",
      "For area memory, when present → docs/context/",
      "For engineering rules → docs/60-engineering/ENGINEERING_STANDARDS.md",
      "For past mistakes → docs/60-engineering/LESSONS.md",
    ],
    output: [
      "The change, with the test and doctor results as evidence.",
      "The card updated, or an explicit statement that no card covers the task.",
    ],
  },
  {
    name: "write-tests",
    title: "Write Tests",
    description:
      "Write tests from acceptance criteria and risk, running each new test red first. Use when a bug fix needs a test that fails without the fix, or a change needs proof it holds. Skip for feature planning, drift reviews, security reviews, and convention checks. Covers behavior only, never Persist internals.",
    goal: "Prove the fix and the behavior with tests derived from acceptance criteria and risk.",
    inputs: ["Acceptance criteria or the bug report.", "The change or diff under test."],
    workflow: [
      "Restate the acceptance criteria and the risks the tests must cover.",
      "For a bug fix, write one test that fails without the fix; run it red before changing code.",
      "Add focused tests for the new behavior and the likely regressions, keeping each test to one behavior.",
      "Run the relevant suite in full, not just the new tests.",
      "If the requirements are too unclear to write a test, stop and ask instead of guessing.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If a test needs Persist internals (symlinks, templates, golden files) → rewrite it against behavior; tests never cover Persist-specific content.",
      "If the fix would change an accepted non-goal → stop and ask for approval.",
    ],
    verification: [
      "Every acceptance criterion maps to at least one test.",
      "The bug-fix test was seen failing without the fix.",
      "The relevant suite passes with the fix in place.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For quality evidence rules → docs/50-quality/QUALITY_GATES.md",
    ],
    output: [
      "The tests added and what each one proves.",
      "The red run and the green run, with commands and results.",
    ],
  },
  {
    name: "create-adr",
    title: "Create ADR",
    description:
      "Record a decision others can check: falsifiable rules, an allowed and a forbidden example, and a filled Applies To list. Use when a change needs a decision recorded. Accept it yourself only when the human stated or confirmed the decision in this conversation; otherwise it stays Proposed. Skip for ADR checks, feature planning, drift reviews, and test writing.",
    goal: "Write a decision record others can check line by line.",
    inputs: [
      "The decision and why it is needed now.",
      "The paths it governs, for its Applies To list.",
    ],
    workflow: [
      "State the context: what decision is needed and why now.",
      "Write the Decision as rules a line of code can pass or fail, with no adjectives that need interpretation.",
      "Give an explicit allowed and a forbidden example for anything easy to misread.",
      "Fill the Applies To list with the exact paths the decision governs.",
      "Record the alternatives considered and the consequences, then `persist adr create` writes it Proposed; run `persist adr accept` yourself only when the human stated or confirmed the decision in this conversation (quote their words in the hand-back), otherwise leave it Proposed and say so.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If a rule cannot be written checkably → say so and propose sharper wording; do not guess.",
      "If the decision changes an accepted ADR → stop and ask, then record it with `persist adr supersede`, never by editing.",
    ],
    verification: [
      "Every Decision sentence passes or fails a line of code without interpretation.",
      "An allowed and a forbidden example exist for each easily misread rule.",
      "The Applies To list names real paths, and the ADR is Proposed unless the hand-back quotes the human's stated or confirmed decision for an acceptance.",
    ],
    resources: [STOP_AND_ASK_RESOURCE, "For prior decisions → docs/adrs/"],
    output: [
      "The path of the ADR.",
      "Whether it is Proposed or accepted on a quoted human confirmation.",
    ],
  },
  {
    name: "drift-review",
    title: "Drift Review",
    description:
      "Give a finished, non-trivial change a fresh-context review against accepted ADRs, module boundaries, new dependencies, tests, and docs. Use when a substantial change is done and needs a second pass before it lands. Skip for ADR writing, feature planning, test writing, and handover notes.",
    goal: "Catch what a finished, non-trivial change got wrong before it lands.",
    inputs: ["The finished diff.", "Test and doctor results, when they exist."],
    workflow: [
      "Review with fresh context: a separate pass from the one that wrote the change.",
      "Run the adr-compliance skill for the ADR part instead of repeating it.",
      "Check module boundaries: nothing crosses ownership the module memory does not allow.",
      "Flag new dependencies, services, storage, or public interfaces that no accepted ADR covers.",
      "Check that tests and docs were updated for the behavior changed.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If a line conflicts with an accepted ADR → change the code; never edit an ADR to fit the code.",
      "If the change is small and single-decision → say so and hand back to the quick check instead.",
    ],
    verification: [
      "Every accepted ADR governing the diff has a verdict through adr-compliance.",
      "Every boundary crossing, new dependency, and missing test or doc update is named or explicitly absent.",
      "No finding rests on a summary; each quotes the file and line.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For accepted decisions → docs/adrs/",
      "For module ownership, when module memory is enabled → docs/30-modules/",
    ],
    output: [
      "Verdict: land, land with fixes, or stop for a human decision.",
      "Finding list with files, lines, and the rule each breaks.",
    ],
  },
  {
    name: "completion-report",
    title: "Completion Report",
    description:
      "Write the completion report for a finished task: files changed, commands run with results, skipped checks, and remaining risks. Use when handing work back as done. Skip for feature planning, drift reviews, test writing, and module docs.",
    goal: "Hand back the evidence that a task finished, honestly.",
    workflow: [
      "List the files changed.",
      "List the commands run with their results.",
      "Name the checks skipped and why each was skipped.",
      "Name the remaining risks.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If doctor or the tests did not run → say so plainly; never claim done without that evidence.",
      "If a warning stays → name it and say why it stays.",
    ],
    verification: [
      "Every file the diff touches is listed.",
      "Every claim about tests or checks names the command and its result.",
      "Skipped checks and remaining risks are explicit, never omitted.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For completion evidence rules → docs/50-quality/QUALITY_GATES.md",
    ],
    output: [
      "The report: files, commands with results, skips, and risks.",
      "The docs updated, if any.",
      'A "Needs your review" list when any exist: Proposed ADRs, assumptions, blocked tasks, and security-sensitive changes, each with the file to open.',
    ],
  },
  {
    name: "module-memory",
    title: "Module Memory",
    description:
      "Plan or update module memory: a module's ownership, boundaries, tests, and governing decisions. Use when scaffolding or revising module memory where it is enabled. Skip for feature planning, ADR writing, drift reviews, and handover notes.",
    goal: "Give each important module a memory its future tasks can start from.",
    inputs: [
      "The module's responsibility boundary.",
      "Its tests, risks, and governing decisions, when known.",
    ],
    workflow: [
      "Confirm module memory is enabled; when no modules directory exists, scaffold it with `persist module create <name>`.",
      "Record what the module owns, its boundaries, and what it explicitly does not own.",
      "Record how the module is tested and which decisions govern it.",
      "Keep DECISIONS and TASKS current when responsibilities, tests, or risks change.",
      "Never overwrite an existing module file: update it in place.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If the work is a single fix inside decided ground → skip this skill and update the area card instead.",
      "If a boundary moves → record the move and the decision behind it; never redraw silently.",
    ],
    verification: [
      "The module's ownership, boundaries, tests, and governing decisions are written down.",
      "No existing module file was overwritten; updates are in place.",
      "A new task in the module can start from this memory without rediscovery.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For module ownership, when module memory is enabled → docs/30-modules/",
      "For prior decisions → docs/adrs/",
    ],
    output: [
      "The module files created or updated.",
      "The boundary or responsibility that changed, or an explicit no-change statement.",
    ],
  },
  {
    name: "plan-feature",
    title: "Plan Feature",
    description:
      "Turn approved requirements into an implementation plan with tasks and a test plan, writing a one-page PRD first when no requirements exist. Use when planning a substantial feature from approved requirements before any implementation begins. Skip for small local changes (implement directly with focused tests), security reviews, and convention checks.",
    goal: "Turn approved requirements into an ordered implementation plan without writing implementation code.",
    inputs: [
      "Approved requirements or feature PRD.",
      "Acceptance criteria.",
      "Known constraints or release target.",
    ],
    workflow: [
      "When no requirements exist, write a one-page PRD first and get it approved; never plan from chat alone.",
      "Restate the objective and acceptance criteria in one paragraph.",
      "Identify the affected modules, docs, templates, and tests.",
      "Record architecture impact and whether a new ADR is needed (propose it with `persist adr create`; accept it yourself only when the human stated or confirmed the decision in this conversation, quoted in the hand-back).",
      "Break the work into ordered tasks, each with explicit completion evidence.",
      "Derive the test plan from acceptance criteria, risks, and likely regressions.",
      "Hand back the PLAN, TASKS, and TEST_PLAN paths before implementing; when working unattended through a goal or task list, continue straight into the first task with the implement-task skill.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If requirements are missing → write the one-page PRD first (this absorbs the retired create-prd skill); if they are contradictory → stop and ask for them.",
      "If a task would change accepted non-goals → stop and ask for approval.",
      "If the request is a small local fix → skip this skill and implement directly with focused tests.",
    ],
    verification: [
      "PLAN states the objective, scope, and architecture impact.",
      "Every task maps to an acceptance criterion or a stated risk.",
      "No implementation code was written.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For completion evidence rules → docs/50-quality/QUALITY_GATES.md",
      "For engineering rules → docs/60-engineering/ENGINEERING_STANDARDS.md",
      "For sensitive scope → docs/20-security/SECURITY_MODEL.md",
      "For prior decisions → docs/adrs/",
      "For module ownership, when module memory is enabled → docs/30-modules/",
    ],
    output: [
      "Paths of the PLAN, TASKS, and TEST_PLAN files written.",
      "One-paragraph summary of scope and the recommended first task.",
    ],
  },
  {
    name: "security-review",
    title: "Security Review",
    description:
      "Review a change for security risks before it is accepted. Use when a change touches a trust boundary — file writes, paths, dependencies, stored secrets, network calls, telemetry, MCP, auth — and needs a decision before merging. Skip for feature planning, test writing, and convention checks.",
    goal: "Find security risks in a change before it is accepted.",
    inputs: ["The change as a diff or summary.", "Test results, when they exist."],
    workflow: [
      "Identify changed trust boundaries: file writes, paths, dependencies, auth, stored secrets, network calls, telemetry, MCP.",
      "Run scripts/scan-secrets.sh over the staged diff and treat matches as blockers until cleared. If scripts/ is unavailable (deleted or cannot execute), perform the same scan by reading the diff directly.",
      "Check validation wherever user-controlled input reaches a file path, query, shell command, or template.",
      "Check new dependencies and configuration changes for risk.",
      "Check that tests cover the security-sensitive behavior.",
      "Classify findings as blockers, risks, or documented tradeoffs.",
      "Hand back the verdict with the finding list.",
    ],
    decisions: [
      "If a credential is present in the change → blocker; stop and ask for its removal.",
      "If user-controlled input reaches a path, query, or shell command unvalidated → blocker.",
      "If the change conflicts with accepted repository memory → stop and ask for a human decision.",
    ],
    verification: [
      "Every trust boundary the change touches has a finding or an explicit all-clear.",
      "Blockers name the exact file and line.",
      "No finding is generic filler.",
    ],
    resources: [
      "For the security model → docs/20-security/SECURITY_MODEL.md",
      "For threat context, when present → docs/20-security/THREAT_MODEL.md",
    ],
    output: [
      "Verdict: accept, accept with risks, or block.",
      "Finding list with files, lines, and severity.",
    ],
    scripts: [
      {
        path: "scripts/scan-secrets.sh",
        content: SECRET_SCAN_SCRIPT,
        executable: true,
      },
    ],
  },
  {
    name: "conventions-adherence",
    title: "Conventions Adherence",
    description:
      "Check a change against the repository's naming conventions and canonical vocabulary instead of reinventing patterns. Use when reviewing a finished change, or before finishing one, to verify it reuses what CONVENTIONS.md names. Skip for planning work, security reviews, and writing new tests.",
    goal: "Verify a change reuses the repository's named vocabulary instead of inventing new patterns.",
    workflow: [
      "Review with fresh context: a separate pass from the one that wrote the change.",
      "Read the Canonical Primitives, Naming Conventions, Rules, and Anti-Patterns sections of CONVENTIONS.md.",
      "For each new component, helper, client, type, or pattern, check whether a named primitive already exists.",
      "Check naming against the documented conventions.",
      "Flag reinvention, divergent naming, and anti-pattern use, each naming the primitive or rule.",
      "Propose a CONVENTIONS.md update when the change establishes a genuinely new shared primitive.",
    ],
    decisions: [
      "If CONVENTIONS.md is missing or still a template → report that first; there is nothing to review against.",
      "If a convention conflicts with an accepted ADR → the ADR wins; stop and ask for a human decision.",
    ],
    verification: [
      "Every finding cites a specific primitive, naming rule, or anti-pattern.",
      "Reinvention of an existing primitive is caught or explicitly absent.",
      "New shared primitives are proposed for documentation, not silently accepted.",
    ],
    resources: [
      "For the vocabulary → docs/60-engineering/CONVENTIONS.md",
      "For past mistakes → docs/60-engineering/LESSONS.md",
    ],
    output: [
      "Finding list citing primitives or rules, or an explicit all-clear.",
      "Proposed CONVENTIONS.md update when one earned it.",
    ],
  },
  {
    name: "chestertons-fence",
    title: "Chesterton's Fence",
    description:
      "Reason about a fence crossing — a change to source logic with no recorded reason for its current shape. Use when a Chesterton fence warning fires on a staged change, when a diff touches logic that looks deliberate but unexplained, or when writing the human-confirmed reason to FENCES.md. Skip for planning work, security reviews, and convention checks.",
    goal: "Decide whether the existing logic is deliberate and record the human-confirmed reason in FENCES.md.",
    inputs: [
      "The staged change or diff the fence warning named.",
      "Access to the human who knows the constraint; name them in the record.",
    ],
    workflow: [
      "List which staged files the fence warning names and read the current logic in each.",
      "For each file, state what the logic does today and what simpler shape tempts the change.",
      "Ask the human why the logic is shaped this way; never infer the constraint from the code.",
      'When the human confirms a real constraint, record it with `persist fence add <path> --why "<reason>" --by <name>`; never hand-write the entry, because the readers parse an exact shape.',
      "When the human confirms the behaviour is accidental rather than deliberate, record that answer with `persist fence add <path> --no-constraint --by <name>`; never pick the answer yourself.",
      "Append the crossing to the entry history with the date, the outcome, and who confirmed it.",
      "Verify the entry against the Verification list and hand back the per-file outcome.",
    ],
    decisions: [
      "If the change is a bug fix → answer one question only: was this behaviour intentional?",
      "If the human does not know or will not confirm → record nothing; a confident guess is worse than an empty file. A deferred crossing stays unrecorded.",
      "If the logic is accidental, not deliberate → record `--no-constraint` with the human's name; it is an answer, and it quiets the file.",
      "A Proposed ADR does not clear the fence; it is reported for review until a human accepts it. Never write an ADR just to quiet a fence warning.",
    ],
    verification: [
      "Every file the warning named has an outcome: fenced with `--why`, answered with `--no-constraint`, or deferred with nothing recorded.",
      "Each fence entry names the human who confirmed the reason.",
      "No Why was inferred from code alone; every reason traces to a human answer.",
      "Each entry was written by `persist fence add`, so the shape the readers parse is guaranteed.",
    ],
    resources: ["For recorded fences and their history → docs/60-engineering/FENCES.md"],
    output: [
      "Outcome per file: fence recorded, accidental (no record), or deferred to a human.",
      "The FENCES.md entry written, or an explicit statement that nothing was recorded.",
    ],
  },
  {
    name: "adr-compliance",
    title: "ADR Compliance",
    description:
      "Check that a change follows the accepted ADRs governing the files it touches: a quick check by default, a full review for large, multi-decision, or money, auth, and data-model changes. Use when a Start here block or persist doctor names a governing ADR, or before calling work done. Skip for writing ADRs, planning, and convention or security reviews.",
    goal: "Prove every accepted ADR that governs a change is followed, or stop before a conflict lands.",
    inputs: [
      "The change: the staged diff, or the commits not yet pushed.",
      'The governing decisions: the "Follow ADR-…" lines Persist handed you and the ADRs persist doctor names.',
    ],
    workflow: [
      'List the governing ADRs: the "Follow ADR-…" lines from the Start here block, plus any ADR `persist doctor` names for the changed files.',
      "Quick check, the default: for each decision, read the changed lines it covers and confirm each one follows it. Judge the operation itself; a comment, name, or summary that claims compliance is not evidence.",
      "Escalate to the full review when the diff is large, several decisions govern it, or it touches money, auth, or the data model.",
      "Full review: read each governing ADR's Decision section in full and rewrite it as rules a line of code can pass or fail.",
      "Full review: check every added line against every rule with fresh context, a sub-agent given only the diff and the rules, and quote the line for each finding.",
      "Full review: flag new dependencies, services, storage, or public interfaces that no accepted ADR covers; each is a decision to record, not a detail.",
      "Resolve every conflict before calling the work done, as the Decisions below say.",
      STOP_AND_ASK_STEP,
    ],
    decisions: [
      "If a line conflicts with an ADR → change the code to follow it; never edit an accepted ADR to fit the code.",
      "If the ADR looks wrong for this change → stop and ask a human; once they agree, record it with `persist adr supersede <old> <new-title>`.",
      "If a decision is too vague to check → report it as unclear and propose sharper wording and an Applies To list; do not guess.",
      "If the change makes a decision no ADR records → propose one with `persist adr create`; run `persist adr accept` yourself only when the human stated or confirmed the decision in this conversation (quote them in the hand-back), otherwise leave it Proposed.",
      "If no accepted ADR governs the change → say so; that is a valid all-clear and needs no review.",
    ],
    verification: [
      "Every governing ADR has a verdict, or the review states that none govern the change.",
      "Every conflict quotes the file, the line, and the rule it breaks.",
      "No verdict rests on a comment, a name, or the author's summary; each rests on the code.",
      "No accepted ADR was edited; any changed decision went through `persist adr supersede`.",
    ],
    resources: [
      STOP_AND_ASK_RESOURCE,
      "For accepted decisions and the paths each one governs (its Applies To section) → docs/adrs/",
    ],
    output: [
      "Per ADR: follows, conflicts (with quoted lines), or unclear.",
      "What was fixed, or the human decision still needed.",
    ],
  },
  {
    name: "context",
    title: "Context Lookup",
    description:
      "Find and record area memory through context cards. Use when starting work in an area with history, when a task names code whose reasons live outside the source, or when finishing work the next task here should find. Skip for small fixes with no reusable reasoning, security reviews, and release planning.",
    goal: "Start from recorded area memory instead of rediscovery, and leave the next task a better card.",
    workflow: [
      'Run `persist context "<task>"` before starting, phrasing the task the way it was asked.',
      "Read only what the matches point at: the Start Here paths first, then the Rules and Pitfalls lines they name. The Always lessons load every session; the lessons for your area arrive with the pointers. If they don't cover what you're doing, open the section of `LESSONS.md` that does (the pointers list them).",
      "When no card covers the task, read the closest decisions and fences the output names instead.",
      "Do the work, then check the diff against the pointed-at rules before calling it done.",
      'When done, create or refresh the area card: `persist context add <name> --purpose "<one line>"` for a new area, otherwise edit the existing card directly.',
      "Put a new lesson under the area it belongs to (create the area with an Applies To list if none fits). Put it under Always only if every task in this repository needs it. When a regression test or a CONVENTIONS rule now enforces a lesson, move it there or delete it, and name the test or rule in the commit. Delete a lesson that describes a temporary state once that state is fixed.",
      "Add the finished task to the card Answers list, phrased the way it was asked.",
      'Run `persist context "<task>"` again to confirm the card is found before calling the work done.',
    ],
    decisions: [
      "If the lookup names no card and no decision → say so; an empty result is a valid answer.",
      "If the area has no card yet → scaffold one with `persist context add`; never overwrite an existing card.",
      "If the card's pointers contradict the code → the code wins today; update the card and say so.",
    ],
    verification: [
      "The lookup ran before any source file was read for the task.",
      "Only pointed-at files were read; no surrounding directory was explored.",
      "The card Answers list holds the finished task in its asked phrasing.",
      "A repeat lookup finds the card for that phrasing.",
    ],
    resources: [
      "For area memory, when present → docs/context/",
      "For past mistakes → docs/60-engineering/LESSONS.md",
    ],
    output: [
      "The card found and the pointed-at files read, or an explicit statement that none covers the task.",
      "The card created or updated, with the new Answers line quoted.",
    ],
  },
];

export function getCatalogSkill(name: string): SkillDefinition | undefined {
  return SKILL_CATALOG.find((skill) => skill.name === name);
}

export function listCatalogSkillNames(): string[] {
  return SKILL_CATALOG.map((skill) => skill.name);
}
