export const HOOKS_DIR = ".persist/hooks";
export const PRE_COMMIT_HOOK_PATH = ".persist/hooks/pre-commit";
export const PRE_PUSH_HOOK_PATH = ".persist/hooks/pre-push";
export const HOOKS_PATH_ACTIVATION_COMMAND = "git config core.hooksPath .persist/hooks";

export const SESSION_START_HOOK_PATH = ".claude/hooks/session-start.sh";
export const CLAUDE_SETTINGS_PATH = ".claude/settings.json";

/**
 * The always-loaded budget both the SessionStart hook and the doctor context-budget check
 * measure against. One constant, two readers: the hook truncates the fence index to what
 * fits inside it, and the check warns when the index no longer fits at all.
 */
export const ALWAYS_LOADED_BUDGET_BYTES = 24 * 1024;

/**
 * The base context the SessionStart hook injects before the fence index. Exported (rather
 * than embedded in the shell template) so the budget check subtracts the exact same bytes
 * the hook emits — `${...}` here is shell, not interpolation.
 */
export const SESSION_START_BASE_CONTEXT =
  "Persist OS repository memory is the source of truth over chat history. Before non-trivial work, read AGENTS.md and the docs it routes to; repository rules override model preference. Accepted ADRs (docs/adrs/): ${adrs:-none yet}. Modules (docs/30-modules/): ${modules:-none yet}. Use the Persist OS CLI commands listed in AGENTS.md (persist feature/adr/module create, persist adr accept and supersede, persist doctor) yourself; do not web-search them. Run 'persist doctor' before claiming work complete.";

/** The label the hook places between the base context and the fence index. */
export const FENCE_INDEX_LABEL =
  " Chesterton fence index (recorded rationale; full history in docs/60-engineering/FENCES.md): ";

/** Marker the hook appends when the fence index is truncated to the budget. */
export const FENCE_INDEX_TRUNCATION_MARKER =
  "... (fence index truncated to the context budget; read docs/60-engineering/FENCES.md)";

/**
 * Render a deterministic POSIX `sh` Claude Code SessionStart hook.
 *
 * Claude Code runs this before the first prompt of every session and injects its stdout
 * `additionalContext` into the model. It lists the repository's accepted ADRs and modules so a fresh
 * agent reliably knows the durable memory exists and where to read it. It is strictly read-only:
 * it only lists files and never modifies anything, makes no network calls, and runs no AI.
 *
 * The Chesterton-fence index (ADR-0010) rides the same injection: fenced paths plus their
 * one-line reasons, flattened to one line — never the full crossing history, which stays on
 * demand in FENCES.md. The index counts against the 24KB always-loaded budget: room is the
 * budget minus the agent files minus the base context minus the index label, so files plus the
 * whole injection stay within budget no matter how large FENCES.md grows. A truncated index
 * carries a marker naming the file. (When files plus base already fill the budget, the marker
 * alone may exceed it by its own ~85 bytes — a state the budget check already warns on.)
 */
export function renderSessionStartHook(): string {
  return `#!/bin/sh
# Persist OS Claude Code SessionStart hook.
# Generated by \`persist init\`. Injects a repository-memory map into every Claude Code session so a
# fresh agent reliably loads durable memory. Wired in .claude/settings.json. Read-only.

adrs=$(ls docs/adrs/ADR-*.md 2>/dev/null | sed 's|.*/||;s|\\.md$||' | tr '\\n' ' ')
modules=$(ls -d docs/30-modules/*/ 2>/dev/null | sed 's|docs/30-modules/||;s|/$||' | tr '\\n' ' ')

# Fence index: one flattened line of "## <path>" / "Why: <reason>" lines from FENCES.md.
# A missing file means no fence crossed yet (FENCES.md is never required), and an empty index
# injects nothing — silence is the correct signal in both cases.
base="${SESSION_START_BASE_CONTEXT}"
context="$base"
full=$(grep -e '^## ' -e '^Why: ' docs/60-engineering/FENCES.md 2>/dev/null | tr '\\n' ' ' | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g')
if [ -n "$full" ]; then
  label="${FENCE_INDEX_LABEL}"
  loaded=$(cat CLAUDE.md AGENTS.md .cursor/rules/persist-memory.mdc 2>/dev/null | wc -c | tr -d ' ')
  room=$((${ALWAYS_LOADED_BUDGET_BYTES} - loaded - $(printf '%s' "$base" | wc -c | tr -d ' ') - $(printf '%s' "$label" | wc -c | tr -d ' ')))
  marker="${FENCE_INDEX_TRUNCATION_MARKER}"
  m=$(printf '%s' "$marker" | wc -c | tr -d ' ')
  if [ "$room" -le 0 ]; then
    fences="$marker"
  elif [ "$(printf '%s' "$full" | wc -c | tr -d ' ')" -le "$room" ]; then
    fences="$full"
  else
    keep=$((room - m))
    if [ "$keep" -lt 0 ]; then
      keep=0
    fi
    fences="$(printf '%s' "$full" | head -c "$keep" | sed 's/\\\\*$//')$marker"
  fi
  context="$base$label$fences"
fi

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\\n' "$context"
`;
}

/**
 * Claude Code settings that wire the SessionStart hook. Generated only when no settings file exists,
 * since the safe write policy never overwrites a user's existing settings.
 */
export function renderClaudeSettings(): string {
  return `${JSON.stringify(
    {
      hooks: {
        SessionStart: [
          {
            matcher: "startup",
            hooks: [{ type: "command", command: `./${SESSION_START_HOOK_PATH}` }],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}

/**
 * Render a deterministic POSIX `sh` pre-commit hook.
 *
 * The hook runs `persist doctor` first, then each configured gate in order. Gates come from
 * `.persist/config.json` (`preCommitGates`), so the toolchain choice stays in user config rather than
 * in core. Doctor warnings are advisory (ADR-0013): the hook continues on exit 0 and exit 1 and
 * fails only on errors (exit 2). The hook does not modify git configuration; activation is a
 * deliberate human step.
 */
export function renderPreCommitHook(gates: string[]): string {
  const lines = [
    "#!/bin/sh",
    "# Persist OS pre-commit hook.",
    "# Generated by `persist init`. Edit gates in .persist/config.json (preCommitGates),",
    "# then re-run `persist init --force` to regenerate this hook.",
    "# Enable once per clone with:",
    `#   ${HOOKS_PATH_ACTIVATION_COMMAND}`,
    "set -e",
    "",
    "# Doctor warnings are advisory: they print but never block the commit.",
    "# Only errors fail the hook. The set +e pair is deliberate — under set -e",
    "# the shell would abort before $? can be read.",
    "set +e",
    "persist doctor",
    "status=$?",
    "set -e",
    '[ "$status" -le 1 ] || exit "$status"',
  ];

  for (const gate of gates) {
    lines.push(gate);
  }

  lines.push("");

  return lines.join("\n");
}

/**
 * Render a deterministic POSIX `sh` pre-push hook — the expensive gate before code leaves the
 * machine. It runs `persist test-gate` (the configured one-shot test command, which skips loudly
 * when unconfigured) and then the push-only gates from `.persist/config.json` (`prePushGates`).
 * Doctor stays on pre-commit: re-running it here would only repeat the same check. Catches commits
 * made with `--no-verify`, on another machine, or before the pre-commit hook was activated. It does
 * not modify git configuration; activation is the same deliberate `core.hooksPath` step.
 */
export function renderPrePushHook(testCommand: string | null, gates: string[]): string {
  const lines = [
    "#!/bin/sh",
    "# Persist OS pre-push hook.",
    "# Generated by `persist init`. The expensive gate before code leaves your machine: it runs",
    "# `persist test-gate` (your configured testCommand, skipped loudly when unset) and your",
    "# push-only gates against everything being pushed (catching commits made with --no-verify",
    "# or before the pre-commit hook was active).",
    "# Edit the test command (testCommand) and gates (prePushGates) in .persist/config.json,",
    "# then re-run `persist init --force` to regenerate this hook.",
    "# Enable once per clone with:",
    `#   ${HOOKS_PATH_ACTIVATION_COMMAND}`,
    "set -e",
    "",
    "persist test-gate",
  ];

  if (testCommand !== null) {
    lines.push(`# testCommand: ${testCommand}`);
  }

  for (const gate of gates) {
    lines.push(gate);
  }

  lines.push("");

  return lines.join("\n");
}
