export const HOOKS_DIR = ".recall/hooks";
export const PRE_COMMIT_HOOK_PATH = ".recall/hooks/pre-commit";
export const HOOKS_PATH_ACTIVATION_COMMAND = "git config core.hooksPath .recall/hooks";

/**
 * Render a deterministic POSIX `sh` pre-commit hook.
 *
 * The hook runs `recall doctor` first, then each configured gate in order. Gates come from
 * `.recall/config.json` (`preCommitGates`), so the toolchain choice stays in user config rather than
 * in core. The hook does not modify git configuration; activation is a deliberate human step.
 */
export function renderPreCommitHook(gates: string[]): string {
  const lines = [
    "#!/bin/sh",
    "# Recall OS pre-commit hook.",
    "# Generated by `recall init`. Edit gates in .recall/config.json (preCommitGates),",
    "# then re-run `recall init --force` to regenerate this hook.",
    "# Enable once per clone with:",
    `#   ${HOOKS_PATH_ACTIVATION_COMMAND}`,
    "set -e",
    "",
    "recall doctor",
  ];

  for (const gate of gates) {
    lines.push(gate);
  }

  lines.push("");

  return lines.join("\n");
}
